### ISSUE TITLE
[iOS - Metal - v6.0.0]  - MLNAnnotationView delay with map panning

### ISSUE THREAD

**Issue by sepperousseau** [maplibre/maplibre-native#2053]
**Describe the bug**
I've been doing some tests with MapLibre Native iOS (6.0.0 (Metal)) And I was just testing some annotations.
Just wondering if this visible delay of annotation views was already there in 5.x.x or someone has the same behaviour ?
The blue ones are MLNAnnotationImage (UIView converted to Image) and the red ones are MLNAnnotationView.
And as you can see the red ones have a slight delay when panning the map. Just like the user location annotation.

**To Reproduce**
Create a MLNAnnotationView and add it to the map.
```
class TestAnnotationView: MLNAnnotationView {
    init(annotation: MLNAnnotation) {
        super.init(annotation: annotation, reuseIdentifier: "test-identifier")
        frame = CGRect(x: 0, y: 0, width: 40, height: 40)
        layer.cornerRadius = 20
        backgroundColor = .red
    }
}
```

**Expected behavior**
I would expect that the MLNAnnotationView and UserLocationAnnotation has slight to no delay as the MLNAnnotationImage?
MLNAnnotationImage will always have better performance but even with 1 annotation it has slight delay.

**Screenshots**
https://github.com/maplibre/maplibre-native/assets/10544377/d7f309cd-04b9-4e72-8b52-e1a1f3e51813

**Platform information (please complete the following information):**
 - OS: iOS
 - Version 6.0.0

Any help is welcome 🙏

**Comment by stefankarschti** [comment]
do you have a fixed set of coordinates that you use for the blue and red circles?

**Comment by sepperousseau** [comment]
> do you have a fixed set of coordinates that you use for the blue and red circles?

Not really. Just some random generated coordinates around a location.
It's the same with 1 point. I'll try to make a test project tomorrow.


https://github.com/maplibre/maplibre-native/assets/10544377/65948bdf-9506-4115-89b1-44b0bd44cbfa

**Comment by stefankarschti** [comment]
Cool. I'd be happy to have a look at the test project!

**Comment by sepperousseau** [comment]
> Cool. I'd be happy to have a look at the test project!

Ok I already created one :D quick and dirty.
I've noticed that the issue isn't there when using no styles url. But with like a standard maptiler vector styles it's there.
I didn't put my api key inside but I guess you have one maybe :D 

[TestMapLibre.zip](https://github.com/maplibre/maplibre-native/files/14057513/TestMapLibre.zip)

**Comment by stefankarschti** [comment]
thanks! I can reproduce the issue on my device. I'm still investigating what the cause might be.

**Comment by stefankarschti** [comment]
So the issue is the way the current implementation replays map transformations on the annotation views that desynchronizes with Metal's multiple frames in flight. I created a tech issue for it: #2082 
We're working on a fix.

**Comment by louwers** [comment]
@stefankarschti Can this issue be closed?

**Comment by stefankarschti** [comment]
No, this is not fixed.

**Comment by nnhubbard** [comment]
@stefankarschti was this fixed? I am still experiencing this issue in the most recent version.

**Comment by louwers** [comment]
@nnhubbard Yes this should be fixed in 6.5.0.

Can you open a new issue? Thanks!

**Comment by Max-Leopold** [comment]
Hey, I also still encounter the same issue. I opened a new issue here: https://github.com/maplibre/maplibre-native/issues/2522
