### ISSUE TITLE
Text rendering performance issues

### ISSUE THREAD

**Issue by Buthrakaur** [maplibre/maplibre-native#3223]
We just migrated from Mapbox to Maplibre and discovered degraded performance especially on iOS (React Native app for both platforms) when zooming in/out or quickly panning the map. We have 3 symbol layers with small/medium/large variants of POI markers to let collision use the largest possible icon available for a nice map UX with hundreds of POIs in a city. I discovered the rendering performance goes massively down when I add a text in the style and especially when I set text halo (`textHaloWidth`, `textHaloColor`) so I had to turn off text halo effects to keep at least some acceptable performance. The Mapbox component seems to have some more performance optimization around text collision detection or text rendering in general. It's surprising the Android performance is still acceptable (even though worse than Mapbox) and it's sluggish on iPhones.

I'd appreciate any recommendations on how to improve the performance by changing the style - I ended up with this:
```jsx
const useTextHalo = Platform.OS === 'android';

const baseStyle: SymbolLayerStyle = {
  textHaloWidth: 2,
  textHaloBlur: 0,
  textAnchor: 'top',
  textMaxWidth: 10,
  textFont: ['get', 'textFont'],
  iconAllowOverlap: false,
  textAllowOverlap: false,
  iconOptional: false,
  iconAnchor: ['get', 'iconAnchor'],
  symbolSortKey: ['get', 'priority'],
  textOffset: [0, 0.1],
};

export const pinLargeStyle: SymbolLayerStyle = {
  ...baseStyle,
  textField: ['get', 'title'],
  textSize: SIZE_L,
  textColor: ['get', 'textColor'],
  textHaloColor: ['get', 'textHaloColor'],
  iconImage: ['get', 'large'],
  iconSize: ICON_SIZE_MULTIPLIER,
};

export const pinMediumStyle: SymbolLayerStyle = {
  ...baseStyle,
  textField: ['get', 'title'],
  iconImage: ['get', 'medium'],
  textSize: ['case', ['==', ['get', 'type'], 'tour'], SIZE_L, SIZE_M],
  textColor: ['get', 'textColor'],
  iconColor: ['get', 'iconColor'],
  textHaloColor: ['get', 'textHaloColor'],
  iconSize: ICON_SIZE_MULTIPLIER,
};

export const pinSmallStyle: SymbolLayerStyle = {
  iconImage: ['get', 'small'],
  iconColor: ['get', 'iconColor'],
  symbolSortKey: ['get', 'priority'],
  iconAnchor: 'center',
  iconSize: ICON_SIZE_MULTIPLIER,
};

if (!useTextHalo) {
  [pinLargeStyle, pinMediumStyle, pinSmallStyle].forEach((style) => {
    delete style.textHaloWidth;
    delete style.textHaloBlur;
    delete style.textHaloColor;
    delete style.textColor;
  });
}


...

  return (
    <>
      <Images images={images} />
      <ShapeSource id={props.layerId} shape={featuresCollection} onPress={onFeaturePress} hitbox={useMemo(() => ({ width: 0, height: 0 }), [])}>
        <SymbolLayer
          id={`SymbolLayer${props.layerId}Small`}
          minZoomLevel={props.minZoomLevel}
          maxZoomLevel={props.maxZoomLevel}
          style={pinSmallStyle}
        />
        <SymbolLayer
          id={`SymbolLayer${props.layerId}Medium`}
          minZoomLevel={props.minZoomLevel}
          maxZoomLevel={props.maxZoomLevel}
          style={pinMediumStyle}
        />
        <SymbolLayer
          id={`SymbolLayer${props.layerId}Large`}
          minZoomLevel={props.minZoomLevel}
          maxZoomLevel={props.maxZoomLevel}
          style={pinLargeStyle}
        />
      </ShapeSource>
    </>
  );
```

This is the intended result which worked well with Mapbox in terms of performance but is not acceptable with MapLibre on iOS:

![image](https://github.com/user-attachments/assets/e97a61b4-a569-45f1-ba2d-02f413264ff0)

**Comment by Buthrakaur** [comment]
I'm not sure if https://github.com/maplibre/maplibre-native/pull/2382 could resolve at least part of the problem but it sounds relevant.

**Comment by louwers** [comment]
Hi @Buthrakaur thanks for sharing your performance-related issue! 

Looping in @sjg-wdw. Maybe the rendering team can have a look at it. Do you have the style available as a JSON? Would you be willing to (privately) share your style with MapLibre developers? We're always interested in heavy styles to help improve performance. We have some [tracing](https://maplibre.org/maplibre-native/docs/book/profiling/tracy-profiling.html) integrated which can be helpful to study what in particular is slowing things down.

**Comment by sjg-wdw** [comment]
Could this be a problem with sorting?  @TimSylvester

**Comment by TimSylvester** [comment]
I wouldn't think so, but it doesn't seem like layout or rendering should be significant in that case.

**Comment by Buthrakaur** [comment]
We were finally able to isolate the issue and prepared a minimum sample repo here: https://github.com/SmartGuideApp/maplibre-test - it's a React Native app so for running it on iOS following sequence needs to be done:
```
npm -i
cd ios
pod install
cd ..
npm run ios
```
The root cause of the performance problem is style having `symbolSortKey: ['get', 'priority']` https://github.com/SmartGuideApp/maplibre-test/blob/main/App.tsx#L6 as suggested by @sjg-wdw .  When it's present the map rendering is slowed down when moving the map and especially when zooming in and out. The rendering is back to normal when this line is commented out. The map style doesn't seem to matter - https://demotiles.maplibre.org/style.json is used in the repo. The performance seems to be impacted more significantly on iOS but some smaller performance impact is visible even on Android phones.

**Comment by sjg-wdw** [comment]
Sort keys are very slow.  Do you need them here?

**Comment by Buthrakaur** [comment]
We are going to stop using them of course as we can sort the features array instead but I believe it would still be great if the performance get fixed at some point of time or at least include a warning in the docs or make this style property obsolete. Mapbox component handles this without any issues - they probably implemented some optimization after the fork was made.

**Comment by TimSylvester** [comment]
It's expected to be slower because things that can normally be grouped together can't be when sorted, but there may still be some problem making it slower than it should be.  From just the screenshot above, it doesn't seem like there are enough instances that it should be noticeable.

**Comment by sjg-wdw** [comment]
I wonder if there are a lot of symbols not appearing.

**Comment by Buthrakaur** [comment]
yes - there's over thousand symbols with 3 layers (small/medium/large icons)

**Comment by sjg-wdw** [comment]
This is starting to make more sense.

Icon and text deconfliction is done in real time in the renderer.  It's a legacy of the original design and it works well if most of the things you give it are going to appear on the screen.

At a certain point, when most of the things you give that deconfliction engine are invisible, you're using it wrong.  It's only meant to make a few very quick decisions.

MapLibre could help fix this by moving deconfliction out of the main rendering loop so it could take as long as it needs.  Working through 1k or even 100k items isn't all that bad if you do it right, just not at 30fps.  We did this in WhirlyGlobe and it was just a matter of memory.

But for the short term, you can avoid sorting or just feed it fewer things to deconflict.

**Comment by TimSylvester** [comment]
I could be wrong, but I don't think sorting directly affects the placement pass.  I'd expect it to only apply to things that end up being selected for rendering.  Possibly we're sorting the entire list of things and only rendering some, but the sort itself should be cheap, even for thousands of items, it's creating drawables and rendering them that seems most likely to be a problem.

**Comment by Buthrakaur** [comment]
@TimSylvester I would expect exactly what you are saying (sorting array of ~thousand items being cheap operation => no perceivable effect of using `symbolSortKey`) but there seems to be some very inefficient code around the sorting or the dynamic data driven sort key retrieval may have some performance penalty?

I recorded a screen recording from our real app if you want to see the difference - I was quickly zooming in and out. This is app version without `symbolSortKey` where zooming is completely smooth:  https://photos.app.goo.gl/QBjdVt4ZbGpH8DqZ8 vs this is app version with `symbolSortKey` where you can see how the zooming is stuttered: https://photos.app.goo.gl/ek57EdQqCnP2JFWo7 .  The only difference is the `symbolSortKey` presence in the symbol style.

**Comment by TimSylvester** [comment]
The actual sort is very cheap, it's actually an ordered insert into a list based on a float key.

The other odd part is it being worse on iOS.  If that's not a red herring, it implies it h as something to do with rendering itself, pretty much everything else is platform-neutral.

Are you able to get a Metal frame capture with profiling?

**Comment by Buthrakaur** [comment]
@TimSylvester I'm not fluent in iOS native development so that would be hard for me honestly but if it's easy for you the sample repository https://github.com/maplibre/maplibre-native/issues/3223#issuecomment-2674844924 has exactly the same perf issue - would that be possible, please?

**Comment by louwers** [comment]
@Buthrakaur Could you try these steps? https://developer.apple.com/documentation/xcode/capturing-a-metal-workload-in-xcode

**Comment by TimSylvester** [comment]
```
$ nvm current
v22.14.0
$ npm -v
10.9.2
$ npm -i
npm <command>

Usage:

npm install        install all the dependencies in your project
npm install <foo>  add the <foo> dependency to your project
npm test           run this project's tests
...
$ npm install
up to date, audited 983 packages in 1s
$ cd ios
$ gem install cocoapods
Successfully installed cocoapods-1.16.2
$ pod install
.../ruby-2.7.0/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': can't find gem cocoapods (>= 0.a) with executable pod (Gem::GemNotFoundException)
$ rvm use macruby
Using .../.rvm/gems/macruby-0.12
$ pod install
.../Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem cocoapods (>= 0.a) with executable pod (Gem::GemNotFoundException)
   from .../Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
   from /usr/local/bin/pod:23:in `<main>'
```

**Comment by TimSylvester** [comment]
`sudo` didn't help, but `bundle install` got me past that error.  The xcode build fails with `Library 'DoubleConversion' not found` though.

**Comment by Buthrakaur** [comment]
@TimSylvester `bundle install` is not the same as `pod install` so I believe that's why you're getting the build error as CocoaPods are still not installed or did you run successfully `pod install` after `bundle install`? After pods are installed please make sure you open the xcworkspace file and not xcodeproj. We actually just pushed a fix to the repo to the Podfile where `$MLRN.post_install(installer)` was missing so please pull the changes. I'm not sure if that may caused the error too.

**Comment by jakub-oone** [comment]
@TimSylvester  Hi Tim, sorry, we had had a mistake in podfile.lock (I was using yarn, not npm). 
So pls: 
- pull repo
- npm install
- cd ios
- pod install

It should work now for you. :)

**Comment by TimSylvester** [comment]
I started over with a fresh clone, and `pod install` pulls `maplibre-react-native (10.0.1)`, but the build still fails with the same dependency error.  I manually updated the pbxproj from 6.10.0 to 6.11.0 and got it to build, but it just produces this:

<img src="https://github.com/user-attachments/assets/a9d0d623-04d9-49da-b3c8-105d379e83d2" width="300"/>

**Comment by Buthrakaur** [comment]
Hi @sjg-wdw , regarding https://github.com/maplibre/maplibre-native/issues/3223#issuecomment-2675600212 

> But for the short term, you can avoid sorting or just feed it fewer things to deconflict.

I just did that (sorted the features array to contain top places first in the array) but discovered there's some issue even with that. The first feature in the array is `Prague Castle` but it sometimes disappears and other features become visible instead when zooming out. You can see a screen recording here: https://photos.app.goo.gl/XLupRpBvEX7onQzS8 . It does behave well when `symbolSortKey` is used btw. Is this some known issue/feature you could explain please or should I report this in a separate bug?

You can see the source code here: https://github.com/SmartGuideApp/maplibre-test/blob/symbol-priority-without-symbolSortKey/App.tsx

**Comment by jakub-oone** [comment]
@TimSylvester Hi Tim, try this:

restart terminal

rm -rf node_modules package-lock.json
npm install
npx react-native start --reset-cache

**Comment by sjg-wdw** [comment]
> Hi [@sjg-wdw](https://github.com/sjg-wdw) , regarding [#3223 (comment)](https://github.com/maplibre/maplibre-native/issues/3223#issuecomment-2675600212)
> 
> > But for the short term, you can avoid sorting or just feed it fewer things to deconflict.
> 
> I just did that (sorted the features array to contain top places first in the array) but discovered there's some issue even with that. The first feature in the array is `Prague Castle` but it sometimes disappears and other features become visible instead when zooming out. You can see a screen recording here: https://photos.app.goo.gl/XLupRpBvEX7onQzS8 . It does behave well when `symbolSortKey` is used btw. Is this some known issue/feature you could explain please or should I report this in a separate bug?
> 
> You can see the source code here: https://github.com/SmartGuideApp/maplibre-test/blob/symbol-priority-without-symbolSortKey/App.tsx

I was suggesting reducing the number of features being handled by the sorting.  I think without the sorting the order you feed things in might not have much bearing.  But I'll defer to Tim who seems to understand this better.

**Comment by TimSylvester** [comment]
I was able to get an Metal trace, but it doesn't show much.  The slowness only seems apparent while transitioning between levels, so it's hard to be sure I got a problematic frame, but one that's busy shows it doing just what we would expect, spending most of the time drawing symbols, particularly SDF, and most of that sampling textures and computing results.  Total GPU time is ~10ms, which is high but not problematic on its own.

<img width="500" alt="Image" src="https://github.com/user-attachments/assets/5b93d3d3-35f7-40da-b4e8-b7375dbcd9ab" />

**Comment by TimSylvester** [comment]
I'm able to profile that app, but the maplibre binary it's pulling in has no symbols. Really, building maplibre from source is needed for tracking down issues.  If you could tweak the maplibre test app to reproduce the problem, that would be more useful.

**Comment by jakub-oone** [comment]
Hi @TimSylvester , I managed to create a native iOS project with settings simulating the performance issue. I hope you can fix it more efficiently now. Here is the link to our repo: [https://github.com/SmartGuideApp/maplibreSymbolSortKey](url) 
Thank you

**Comment by TimSylvester** [comment]
I'm able to run that, but I didn't have any luck getting symbols to load into it, and I get the same small item.  Are you able to try this on different iOS devices?

<img width="500" alt="Image" src="https://github.com/user-attachments/assets/1d920d06-8302-469e-8a4e-ef2493d7554a" />

I think to get any further, you'll need to pull in MapLibre as a submodule and build it from source as part of your workspace.  I think that'll build a static library by default, though, which changes how loading works.

**Comment by Buthrakaur** [comment]
Hi @TimSylvester , thanks for reviewing the app. Could you please clarify next steps - do you need any more information from us? There's still the "more info needed" label present on this issue..

**Comment by louwers** [comment]
@Buthrakaur I removed the label since @TimSylvester was able to investigate the issue now. No more information needed at this point I think, thanks for reporting this.

**Comment by Buthrakaur** [comment]
Thanks. We implemented a workaround to the issue I describer here https://github.com/maplibre/maplibre-native/issues/3223#issuecomment-2690102580 - we added yet another symbol layer containing symbols with highest priority. This resolves the most visible issue but doesn't fix the problem completely so we would be glad to get this fix at some time in the future and get back to use the `symbolSortKey` again to fix the problem completely. Using clustering or filtering is unfortunately not possible in our case - that would massively harm the UX.

**Comment by TimSylvester** [comment]
#3576 should significantly improve this scenario on iOS, though it's only partly addressing the problem.
